### ISSUE TITLE
Jetpack 5.1 support?

### ISSUE THREAD

**Issue by AndreV84** [IntelRealSense/realsense_mipi_platform_driver#162]
is Jetpack 5.1 supported?

**Comment by dmipx** [comment]
We have support for 5.0.2 and we will try to update to latest.
As from release notes of 5.1.1 i didn't see any changes that can be incompatible but we did not verified it.

**Comment by dmipx** [comment]
Hi.
We added 5.1.2 support to dev branch.
JP 6 is on going (see open PR #182)
