### ISSUE TITLE
Are the tegra_sinterface and port_index incorrect?

### ISSUE THREAD

**Issue by sancAslan** [IntelRealSense/realsense_mipi_platform_driver#163]
In the modification to the [device tree](https://github.com/IntelRealSense/realsense_mipi_platform_driver/blob/Jetpack-5.0.2/hardware/nvidia/platform/t19x/galen/kernel-dts/5.0.2/0001-Porting-dts-to-jetpack-5.0.2.patch) the tegra_sinterface for device d4m1 is set to "serial_e" (line 267) but the corresponding CSI channel endpoint is set to port-index = <0> (line 451) which corresponds to "serial _a" on the Xavier.

How are the drivers receiving RGB data in this case?

**Comment by dmipx** [comment]
As you can trace, from line [L253](https://github.com/IntelRealSense/realsense_mipi_platform_driver/blob/Jetpack-5.0.2/hardware/nvidia/platform/t19x/galen/kernel-dts/5.0.2/0001-Porting-dts-to-jetpack-5.0.2.patch#L253):
i2c@1->d4m1->ports->port@0->port-index = <1>;
