### ISSUE TITLE
x86 platform support

### ISSUE THREAD

**Issue by vanthome** [IntelRealSense/realsense_mipi_platform_driver#169]
Is there any x86 platform support for the D457?

BG, Thomas

**Comment by dmipx** [comment]
Hi.
Yes, we have AldreLake platform integrated, You will need ADL-P with mipi connector and max9295/6 SerDes for GMSL.
Currently it's hosted on Intel's IPU6 github:
https://github.com/intel/ipu6-drivers/pull/73
https://github.com/intel/ipu6-drivers/pull/72

**Comment by dmipx** [comment]
Specifically there is one vendor that we are working with - AXIOMTEK
https://www.axiomtek.com/Default.aspx?MenuId=Products&FunctionId=ProductView&ItemId=26840&upcat=403
That platform is under active maintenance.
