### ISSUE TITLE
The D457 image is abnormal

### ISSUE THREAD

**Issue by edu118** [IntelRealSense/realsense_mipi_platform_driver#208]
We connected D457 to max9296 and then connect to Jetson AGX Orin, but 848*480 resolution images were abnormal, and other resolutions were normal
![diagram](https://github.com/IntelRealSense/realsense_mipi_platform_driver/assets/163959861/31599c06-4951-4ab7-84be-916e772220b4)
![image](https://github.com/IntelRealSense/realsense_mipi_platform_driver/assets/163959861/7d0dbbb7-cb43-413e-b373-fe34451a1bf4)

**Comment by Nir-Az** [comment]
Hi @edu118 
Cna you share which driver version is used? and which JP?

**Comment by edu118** [comment]
D457 Camera firmware version: 5.16.01
JP is 5.1.2

**Comment by Nir-Az** [comment]
@edu118 driver version is the last released driver?

**Comment by edu118** [comment]
Hi @Nir-Az
yes

**Comment by Nir-Az** [comment]
Thanks for the info, we will investigate the issue

**Comment by edu118** [comment]
Hi @Nir-Az
Please help to take a look as soon as possible. Our project is a bit urgent, thank you！

**Comment by Nir-Az** [comment]
Can you please also share the output of 
modinfo d4xx
And state how many cameras are connected and which deserializer is connected at your setup?

**Comment by edu118** [comment]
![image](https://github.com/IntelRealSense/realsense_mipi_platform_driver/assets/163959861/423bb6f7-e732-4708-ba82-2c74acd112d5)
4 D457 cameras
2 max9296

**Comment by edu118** [comment]
![f825ba1709c84cfe4d464afbe435bee7c86821b7](https://github.com/IntelRealSense/realsense_mipi_platform_driver/assets/163959861/636d4887-829e-471c-ad94-b0174263aab9)

**Comment by dmipx** [comment]
Its resolved with https://github.com/IntelRealSense/realsense_mipi_platform_driver/pull/217
