### ISSUE TITLE
JetPack 6.0 rev. 1, L4T 36.3.0 Support

### ISSUE THREAD

**Issue by yurii-drevnytskyi-dianomix** [IntelRealSense/realsense_mipi_platform_driver#210]
Hi everybody,
Are you going to add support for the [nvidia jetson linux 36.3](https://developer.nvidia.com/embedded/jetson-linux-r363) ?

**Comment by dmipx** [comment]
Hi. It's already merged to dev branch.

**Comment by Nir-Az** [comment]
@yurii-drevnytskyi-dianomix  you are welcome to try building `dev` branch from source according to the instructions and let us know how it goes 👍
