### ISSUE TITLE
Jetson cannot recognize the mouse and keyboard after installing the driver

### ISSUE THREAD

**Issue by songWell** [IntelRealSense/realsense_mipi_platform_driver#227]
HW: AGX Orin 64GB developer kit
SW: Jetpack 6.0

I followed the step [https://github.com/IntelRealSense/realsense_mipi_platform_driver/blob/dev/README_JP6.md#build-environment-prerequisites](https://github.com/IntelRealSense/realsense_mipi_platform_driver/blob/dev/README_JP6.md#build-environment-prerequisites)

builded Image in My host PC and copy Image and other files to Jetson. 
followed these step

> # enable RealSense extra formats and metadata
> sudo cp -r ~/extra /lib/modules/$(uname -r)/
> # enable RealSense MIPI support for D457 GMSL
> sudo cp -r ~/updates /lib/modules/$(uname -r)/
> sudo cp ~/boot/tegra234-camera-d4xx-overlay.dtbo /boot/
> sudo cp ./boot/dtb/tegra234-p3737-0000+p3701-0000-nv.dtb /boot/tegra234-p3737-0000+p3701-0000-nv.dtb
> # If "--dev-dbg" option is enabled, kernel will be modified. So, copy the 'Image' as well. If not enabled, no need to copy.
> sudo cp ./boot/Image /boot/Image
> # Enable d4xx overlay:
> sudo /opt/nvidia/jetson-io/config-by-hardware.py -n 2="Jetson RealSense Camera D457"
> 
> # Enable d4xx autoload:
> echo "d4xx" | sudo tee /etc/modules-load.d/d4xx.conf
> # Enable depmod scan for "extra" modules
> # original file content: cat /etc/depmod.d/ubuntu.conf -- search updates ubuntu built-in
> sudo sed -i 's/search updates/search extra updates/g' /etc/depmod.d/ubuntu.conf
> # update driver cache
> sudo depmod
> 
> #Reboot machine.
> sudo reboot

After restarting, Jetson cannot recognize the mouse and keyboard, and the mouse and keyboard have no response. Is there anything I need to pay attention to? 
Need advice, thanks.

**Comment by dmipx** [comment]
Hi,
you need to revert https://github.com/IntelRealSense/realsense_mipi_platform_driver/commit/81c2304ad01a53dcbd85a2bf08b5941f0e677306 commit.
The issue is that after kernel modified, you have to replace all kernel modules to be compatible.

**Comment by songWell** [comment]
Thank you very much. I recompiled with the build_all.sh, and did not copy the Image, successfully started realsense-viewer, and successfully visualized the IMU data.
Thanks again.
